import { defineConfig } from 'oxlint';

const eslintConfig = defineConfig({
  overrides: [
    {
      files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
      rules: {
        'constructor-super': 'off',
        'getter-return': 'off',
        'no-class-assign': 'off',
        'no-const-assign': 'off',
        'no-dupe-class-members': 'off',
        'no-dupe-keys': 'off',
        'no-func-assign': 'off',
        'no-import-assign': 'off',
        'no-new-native-nonconstructor': 'off',
        'no-obj-calls': 'off',
        'no-setter-return': 'off',
        'no-this-before-super': 'off',
        'no-unreachable': 'off',
        'no-unsafe-negation': 'off',
        'no-var': 'error',
        'no-with': 'off',
        'prefer-const': 'error',
        'prefer-rest-params': 'error',
        'prefer-spread': 'error',
      },
    },
  ],
  plugins: ['eslint'],
  rules: {
    'constructor-super': 'error',
    'default-case-last': 'warn',
    'default-param-last': 'warn',
    'for-direction': 'error',
    'getter-return': 'error',
    'no-array-constructor': 'error',
    'no-async-promise-executor': 'error',
    'no-case-declarations': 'error',
    'no-class-assign': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': 'error',
    'no-const-assign': 'error',
    'no-constant-binary-expression': 'error',
    'no-constant-condition': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-delete-var': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-else-if': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-empty': 'error',
    'no-empty-character-class': 'error',
    'no-empty-function': 'error',
    'no-empty-pattern': 'error',
    'no-empty-static-block': 'error',
    'no-ex-assign': 'error',
    'no-extra-boolean-cast': 'error',
    'no-fallthrough': 'error',
    'no-func-assign': 'error',
    'no-global-assign': 'error',
    'no-import-assign': 'error',
    'no-invalid-regexp': 'error',
    'no-irregular-whitespace': 'error',
    'no-loss-of-precision': 'error',
    'no-misleading-character-class': 'error',
    'no-new-native-nonconstructor': 'error',
    'no-nonoctal-decimal-escape': 'error',
    'no-obj-calls': 'error',
    'no-prototype-builtins': 'error',
    'no-redeclare': 'warn',
    'no-regex-spaces': 'error',
    'no-self-assign': 'error',
    'no-setter-return': 'error',
    'no-shadow': 'warn',
    'no-shadow-restricted-names': 'error',
    'no-sparse-arrays': 'error',
    'no-this-before-super': 'error',
    'no-unassigned-vars': 'error',
    'no-unexpected-multiline': 'error',
    'no-unreachable': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'no-unsafe-optional-chaining': 'error',
    'no-unused-expressions': 'error',
    'no-unused-labels': 'error',
    'no-unused-private-class-members': 'error',
    'no-unused-vars': [
      'error',
      {
        args: 'all',
        argsIgnorePattern: '^_',
        caughtErrors: 'all',
        caughtErrorsIgnorePattern: '^_',
        destructuredArrayIgnorePattern: '^_',
        ignoreRestSiblings: true,
        varsIgnorePattern: '^_',
      },
    ],
    'no-useless-backreference': 'error',
    'no-useless-catch': 'error',
    'no-useless-escape': 'error',
    'no-with': 'error',
    'prefer-arrow-callback': 'warn',
    'preserve-caught-error': 'error',
    'require-yield': 'error',
    'use-isnan': 'error',
    'valid-typeof': 'error',
  },
});

const typescriptConfig = defineConfig({
  plugins: ['typescript'],
  rules: {
    'typescript/array-type': [
      'warn',
      {
        default: 'generic',
        readonly: 'generic',
      },
    ],
    'typescript/ban-ts-comment': 'error',
    'typescript/ban-tslint-comment': 'error',
    'typescript/class-literal-property-style': 'error',
    'typescript/consistent-generic-constructors': 'error',
    'typescript/consistent-indexed-object-style': 'error',
    'typescript/consistent-type-assertions': 'error',
    'typescript/consistent-type-definitions': 'error',
    'typescript/consistent-type-imports': [
      'warn',
      {
        fixStyle: 'inline-type-imports',
        prefer: 'type-imports',
      },
    ],
    'typescript/no-confusing-non-null-assertion': 'error',
    'typescript/no-duplicate-enum-values': 'error',
    'typescript/no-empty-object-type': 'error',
    'typescript/no-explicit-any': 'error',
    'typescript/no-extra-non-null-assertion': 'error',
    'typescript/no-import-type-side-effects': 'warn',
    'typescript/no-inferrable-types': 'error',
    'typescript/no-misused-new': 'error',
    'typescript/no-namespace': 'error',
    'typescript/no-non-null-asserted-optional-chain': 'error',
    'typescript/no-require-imports': 'error',
    'typescript/no-this-alias': 'error',
    'typescript/no-unnecessary-type-constraint': 'error',
    'typescript/no-unsafe-declaration-merging': 'error',
    'typescript/no-unsafe-function-type': 'error',
    'typescript/no-wrapper-object-types': 'error',
    'typescript/prefer-as-const': 'error',
    'typescript/prefer-for-of': 'error',
    'typescript/prefer-function-type': 'error',
    'typescript/prefer-namespace-keyword': 'error',
    'typescript/triple-slash-reference': 'error',
  },
});

const sonarConfig = defineConfig({
  jsPlugins: ['eslint-plugin-sonarjs'],
  rules: {
    'sonarjs/anchor-precedence': 'error',
    'sonarjs/argument-type': 'error',
    'sonarjs/arguments-order': 'error',
    'sonarjs/array-callback-without-return': 'error',
    'sonarjs/assertions-in-tests': 'error',
    'sonarjs/async-test-assertions': 'error',
    'sonarjs/aws-apigateway-public-api': 'error',
    'sonarjs/aws-ec2-rds-dms-public': 'error',
    'sonarjs/aws-ec2-unencrypted-ebs-volume': 'error',
    'sonarjs/aws-efs-unencrypted': 'error',
    'sonarjs/aws-iam-all-privileges': 'error',
    'sonarjs/aws-iam-privilege-escalation': 'error',
    'sonarjs/aws-iam-public-access': 'error',
    'sonarjs/aws-opensearchservice-domain': 'error',
    'sonarjs/aws-rds-unencrypted-databases': 'error',
    'sonarjs/aws-restricted-ip-admin-access': 'error',
    'sonarjs/aws-s3-bucket-granted-access': 'error',
    'sonarjs/aws-s3-bucket-insecure-http': 'error',
    'sonarjs/aws-s3-bucket-public-access': 'error',
    'sonarjs/aws-s3-bucket-versioning': 'error',
    'sonarjs/aws-sagemaker-unencrypted-notebook': 'error',
    'sonarjs/aws-sns-unencrypted-topics': 'error',
    'sonarjs/aws-sqs-unencrypted-queue': 'error',
    'sonarjs/bitwise-operators': 'error',
    'sonarjs/block-scoped-var': 'error',
    'sonarjs/call-argument-line': 'error',
    'sonarjs/chai-determinate-assertion': 'error',
    'sonarjs/class-name': 'error',
    'sonarjs/code-eval': 'error',
    'sonarjs/cognitive-complexity': 'error',
    'sonarjs/comma-or-logical-or-case': 'error',
    'sonarjs/concise-regex': 'error',
    'sonarjs/constructor-for-side-effects': 'error',
    'sonarjs/content-length': 'error',
    'sonarjs/content-security-policy': 'error',
    'sonarjs/cookie-no-httponly': 'error',
    'sonarjs/cors': 'error',
    'sonarjs/csrf': 'error',
    'sonarjs/deprecation': 'error',
    'sonarjs/different-types-comparison': 'error',
    'sonarjs/disabled-auto-escaping': 'error',
    'sonarjs/disabled-resource-integrity': 'error',
    'sonarjs/disabled-timeout': 'error',
    'sonarjs/dompurify-unsafe-config': 'error',
    'sonarjs/duplicates-in-character-class': 'error',
    'sonarjs/dynamically-constructed-templates': 'error',
    'sonarjs/empty-string-repetition': 'error',
    'sonarjs/encryption-secure-mode': 'error',
    'sonarjs/existing-groups': 'error',
    'sonarjs/file-permissions': 'error',
    'sonarjs/file-uploads': 'error',
    'sonarjs/fixme-tag': 'error',
    'sonarjs/for-loop-increment-sign': 'error',
    'sonarjs/function-inside-loop': 'error',
    'sonarjs/function-return-type': 'error',
    'sonarjs/future-reserved-words': 'error',
    'sonarjs/generator-without-yield': 'error',
    'sonarjs/hardcoded-secret-signatures': 'error',
    'sonarjs/hashing': 'error',
    'sonarjs/hooks-before-test-cases': 'error',
    'sonarjs/in-operator-type-error': 'error',
    'sonarjs/inconsistent-function-call': 'error',
    'sonarjs/index-of-compare-to-positive-number': 'error',
    'sonarjs/insecure-cookie': 'error',
    'sonarjs/insecure-jwt-token': 'error',
    'sonarjs/inverted-assertion-arguments': 'error',
    'sonarjs/jsx-no-leaked-render': 'error',
    'sonarjs/label-position': 'error',
    'sonarjs/link-with-target-blank': 'error',
    'sonarjs/max-switch-cases': 'error',
    'sonarjs/misplaced-loop-counter': 'error',
    'sonarjs/new-operator-misuse': 'error',
    'sonarjs/no-all-duplicated-branches': 'error',
    'sonarjs/no-alphabetical-sort': 'error',
    'sonarjs/no-angular-bypass-sanitization': 'error',
    'sonarjs/no-array-delete': 'error',
    'sonarjs/no-associative-arrays': 'error',
    'sonarjs/no-async-constructor': 'error',
    'sonarjs/no-case-label-in-switch': 'error',
    'sonarjs/no-clear-text-protocols': 'error',
    'sonarjs/no-code-after-done': 'error',
    'sonarjs/no-collection-size-mischeck': 'error',
    'sonarjs/no-control-regex': 'error',
    'sonarjs/no-dead-store': 'error',
    'sonarjs/no-delete-var': 'error',
    'sonarjs/no-duplicate-in-composite': 'error',
    'sonarjs/no-duplicate-test-title': 'error',
    'sonarjs/no-duplicated-branches': 'error',
    'sonarjs/no-element-overwrite': 'error',
    'sonarjs/no-empty-after-reluctant': 'error',
    'sonarjs/no-empty-alternatives': 'error',
    'sonarjs/no-empty-character-class': 'error',
    'sonarjs/no-empty-collection': 'error',
    'sonarjs/no-empty-group': 'error',
    'sonarjs/no-empty-test-file': 'error',
    'sonarjs/no-empty-test-title': 'error',
    'sonarjs/no-equals-in-for-termination': 'error',
    'sonarjs/no-exclusive-tests': 'error',
    'sonarjs/no-extra-arguments': 'error',
    'sonarjs/no-fallthrough': 'error',
    'sonarjs/no-floating-point-equality': 'error',
    'sonarjs/no-forced-browser-interaction': 'error',
    'sonarjs/no-global-this': 'error',
    'sonarjs/no-globals-shadowing': 'error',
    'sonarjs/no-gratuitous-expressions': 'error',
    'sonarjs/no-hardcoded-ip': 'error',
    'sonarjs/no-hardcoded-passwords': 'error',
    'sonarjs/no-hardcoded-secrets': 'error',
    'sonarjs/no-hook-setter-in-body': 'error',
    'sonarjs/no-identical-conditions': 'error',
    'sonarjs/no-identical-expressions': 'error',
    'sonarjs/no-identical-functions': 'error',
    'sonarjs/no-ignored-exceptions': 'error',
    'sonarjs/no-ignored-return': 'error',
    'sonarjs/no-implicit-global': 'error',
    'sonarjs/no-in-misuse': 'error',
    'sonarjs/no-incompatible-assertion-types': 'error',
    'sonarjs/no-incomplete-assertions': 'error',
    'sonarjs/no-internal-api-use': 'error',
    'sonarjs/no-invalid-regexp': 'error',
    'sonarjs/no-invariant-returns': 'error',
    'sonarjs/no-inverted-boolean-check': 'error',
    'sonarjs/no-labels': 'error',
    'sonarjs/no-literal-call': 'error',
    'sonarjs/no-mime-sniff': 'error',
    'sonarjs/no-misleading-array-reverse': 'error',
    'sonarjs/no-misleading-character-class': 'error',
    'sonarjs/no-nested-assignment': 'error',
    'sonarjs/no-nested-conditional': 'error',
    'sonarjs/no-nested-functions': 'error',
    'sonarjs/no-nested-template-literals': 'error',
    'sonarjs/no-os-command-from-path': 'error',
    'sonarjs/no-parameter-reassignment': 'error',
    'sonarjs/no-primitive-wrappers': 'error',
    'sonarjs/no-redundant-assignments': 'error',
    'sonarjs/no-redundant-boolean': 'error',
    'sonarjs/no-redundant-jump': 'error',
    'sonarjs/no-redundant-optional': 'error',
    'sonarjs/no-referrer-policy': 'error',
    'sonarjs/no-regex-spaces': 'error',
    'sonarjs/no-same-argument-assert': 'error',
    'sonarjs/no-same-line-conditional': 'error',
    'sonarjs/no-selector-parameter': 'error',
    'sonarjs/no-session-cookies-on-static-assets': 'error',
    'sonarjs/no-skipped-tests': 'error',
    'sonarjs/no-small-switch': 'error',
    'sonarjs/no-table-as-layout': 'error',
    'sonarjs/no-trivial-assertions': 'error',
    'sonarjs/no-try-promise': 'error',
    'sonarjs/no-undefined-argument': 'error',
    'sonarjs/no-unenclosed-multiline-block': 'error',
    'sonarjs/no-uniq-key': 'error',
    'sonarjs/no-unthrown-error': 'error',
    'sonarjs/no-unused-collection': 'error',
    'sonarjs/no-use-of-empty-return-value': 'error',
    'sonarjs/no-useless-catch': 'error',
    'sonarjs/no-useless-increment': 'error',
    'sonarjs/no-useless-intersection': 'error',
    'sonarjs/no-useless-react-setstate': 'error',
    'sonarjs/no-weak-cipher': 'error',
    'sonarjs/no-weak-keys': 'error',
    'sonarjs/non-existent-operator': 'error',
    'sonarjs/null-dereference': 'error',
    'sonarjs/object-alt-content': 'error',
    'sonarjs/post-message': 'error',
    'sonarjs/prefer-default-last': 'error',
    'sonarjs/prefer-promise-shorthand': 'error',
    'sonarjs/prefer-regexp-exec': 'error',
    'sonarjs/prefer-single-boolean-return': 'error',
    'sonarjs/prefer-specific-assertions': 'error',
    'sonarjs/prefer-type-guard': 'error',
    'sonarjs/prefer-while': 'error',
    'sonarjs/production-debug': 'error',
    'sonarjs/pseudo-random': 'error',
    'sonarjs/public-static-readonly': 'error',
    'sonarjs/publicly-writable-directories': 'error',
    'sonarjs/reduce-initial-value': 'error',
    'sonarjs/redundant-type-aliases': 'error',
    'sonarjs/regex-complexity': 'error',
    'sonarjs/review-blockchain-mnemonic': 'error',
    'sonarjs/session-regeneration': 'error',
    'sonarjs/single-char-in-character-classes': 'error',
    'sonarjs/single-character-alternation': 'error',
    'sonarjs/slow-regex': 'error',
    'sonarjs/sql-queries': 'error',
    'sonarjs/stable-tests': 'error',
    'sonarjs/stateful-regex': 'error',
    'sonarjs/strict-transport-security': 'error',
    'sonarjs/super-linear-regex': 'error',
    'sonarjs/table-header': 'error',
    'sonarjs/table-header-reference': 'error',
    'sonarjs/test-check-exception': 'error',
    'sonarjs/unused-import': 'error',
    'sonarjs/unused-named-groups': 'error',
    'sonarjs/unverified-certificate': 'error',
    'sonarjs/unverified-hostname': 'error',
    'sonarjs/updated-const-var': 'error',
    'sonarjs/updated-loop-counter': 'error',
    'sonarjs/use-type-alias': 'error',
    'sonarjs/weak-ssl': 'error',
    'sonarjs/x-powered-by': 'error',
    'sonarjs/xml-parser-xxe': 'error',
  },
});

const genericPerfectionistSortRules = [
  'perfectionist/sort-array-includes',
  'perfectionist/sort-classes',
  'perfectionist/sort-decorators',
  'perfectionist/sort-enums',
  'perfectionist/sort-export-attributes',
  'perfectionist/sort-exports',
  'perfectionist/sort-heritage-clauses',
  'perfectionist/sort-import-attributes',
  'perfectionist/sort-interfaces',
  'perfectionist/sort-intersection-types',
  'perfectionist/sort-jsx-props',
  'perfectionist/sort-maps',
  'perfectionist/sort-modules',
  'perfectionist/sort-named-exports',
  'perfectionist/sort-named-imports',
  'perfectionist/sort-object-types',
  'perfectionist/sort-objects',
  'perfectionist/sort-sets',
  'perfectionist/sort-switch-case',
  'perfectionist/sort-union-types',
  'perfectionist/sort-variable-declarations',
] as const;

const genericSortRulesWithoutPartition = new Set<(typeof genericPerfectionistSortRules)[number]>([
  'perfectionist/sort-jsx-props',
  'perfectionist/sort-switch-case',
]);

const perfectionistConfig = defineConfig({
  jsPlugins: ['eslint-plugin-perfectionist'],
  rules: {
    //Set up a specific import order that we generally want to adhere to.
    //This makes it easier to recognize where an import is coming from.
    'perfectionist/sort-imports': [
      'warn',
      {
        groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index', 'unknown'],
        ignoreCase: true,
        newlinesBetween: 0,
        order: 'asc',
        partitionByComment: true,
        type: 'natural',
      },
    ],
    //Extend the default recommended rules to include comment partioning to allow for comments being used for explanatory purposes.
    ...Object.fromEntries(
      genericPerfectionistSortRules.map((rule) => [
        rule,
        [
          'error',
          genericSortRulesWithoutPartition.has(rule)
            ? {
                type: 'natural',
              }
            : { partitionByComment: true, type: 'natural' },
        ],
      ]),
    ),
    //Turning this rule off as recommended in the perfectionist documention as it is handled by perfectionist in the following rules:
    //sort-interfaces:  https://perfectionist.dev/rules/sort-interfaces
    //sort-objects:  https://perfectionist.dev/rules/sort-object-types
    '@typescript-eslint/adjacent-overload-signatures': 'off',
  },
});

const importConfig = defineConfig({
  plugins: ['import'],
  rules: {
    'import/consistent-type-specifier-style': ['warn', 'prefer-top-level'],
    'import/default': 'error',
    'import/namespace': 'error',
    'import/no-duplicates': 'warn',
    'import/no-named-as-default': 'warn',
    'import/no-named-as-default-member': 'warn',
  },
});

const demorganConfig = defineConfig({
  jsPlugins: ['eslint-plugin-de-morgan'],
  rules: {
    'de-morgan/no-negated-conjunction': 'error',
    'de-morgan/no-negated-disjunction': 'error',
  },
});

const dependConfig = defineConfig({
  jsPlugins: ['eslint-plugin-depend'],
  rules: {
    'depend/ban-dependencies': 'error',
  },
});

export const base = defineConfig({
  categories: {
    correctness: 'off',
  },
  env: {
    browser: true,
    builtin: true,
    es2024: true,
    node: true,
  },
  extends: [
    eslintConfig,
    typescriptConfig,
    sonarConfig,
    perfectionistConfig,
    importConfig,
    demorganConfig,
    dependConfig,
  ],
  options: {
    //typeAware: true,
  },
});
