name: Release
permissions:
  contents: write
  pull-requests: write
  id-token: write

on:
  workflow_run:
    workflows: ['Test']
    types: [completed]
    branches:
      - 'main'
      - 'next'

env:
  # The node version to release with, generally the latest LTS
  release_node: 24.x

jobs:
  release:
    name: Release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # https://github.com/pnpm/action-setup/releases/tag/v6.0.3
        with:
          version: 11.0.8

      - name: Setup Node.js ${{ env.release_node }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.release_node }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0 Commit hash taken from https://github.com/changesets/action/tree/v1/src
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
